import './globals.css'

import { Roboto_Mono } from 'next/font/google'
 
const roboto = Roboto_Mono({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
  style: ['italic', 'normal'], 
  display: 'swap',
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {  
  return (
    <html lang="en" className={`bg-white h-full w-full ${roboto.className}`}>
      <body className="bg-white h-full w-full text-black">{children}</body>
    </html>
  )
}
