import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {  
  return (
    <html lang="en" className='text-white h-full w-full'>
      <body className="${inter.className} bg-white h-full w-full text-black">{children}</body>
    </html>
  )
}
